name: publish_docs
description: Publish your documentation to GitHub Pages!
version: 0.0.2+3
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ^3.4.1
  convert:
    git:
      url: https://github.com/dart-lang/convert.git
      ref: fix-47
  dartdoc:
    git:
      url: https://github.com/Cliabhach/dartdoc.git
      ref: model-element-fixes
  git: 2.0.0
  mime: ^1.0.2

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

dependency_overrides:
  convert:
    git:
      url: https://github.com/dart-lang/convert.git
      ref: fix-47
