name: publish_docs
description: Publish your documentation to a GitHub Pages branch!
repository: https://github.com/Cliabhach/publish_docs/
version: 0.2.4+17
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

executables:
  # General-purpose 'info' script
  publish_docs:
  # Generate new docs locally in doc/api/
  docs_generate: generate
  # Create a commit on the GitHub Pages branch
  docs_commit: commit

dependencies:
  analyzer: ^3.4.1
  convert:
    git:
      url: https://github.com/dart-lang/convert.git
      ref: fix-47
  dartdoc:
    git:
      url: https://github.com/Cliabhach/dartdoc.git
      ref: model-element-fixes
  git: 2.0.0
  mime: ^1.0.2

dev_dependencies:
  coverage: ^1.2.0
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^2.4.0

dependency_overrides:
  convert:
    git:
      url: https://github.com/dart-lang/convert.git
      ref: fix-47
